name: .NET CI Sonar

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Start Sonar analysis
        run: dotnet-sonarscanner begin /k:"seu-usuario_ou-org_nome-do-repo" /o:"seu-usuario_ou-org" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

      - name: Restore and build
        run: dotnet build --no-incremental

      - name: Run tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: End Sonar analysis
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
