name: .NET Tests

on:
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Execute tests
        run: bash scripts/run_tests.sh
