name: Publish .NET Packages

on:
  push:
    paths:
      - 'src/Packages/**'  
    branches:
      - main  
  workflow_dispatch:

jobs:
  build-and-publish-packages:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuration .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

      - name: Restore dependencies
        run: dotnet restore src/Packages

      - name: Compile the project
        run: dotnet build src/Packages --configuration Release --no-restore

      - name: Create and publish only updated packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          get_latest_version() {
            local package_name="$1"
            local owner_type="${{ github.repository_owner_type }}"
            local owner_path

            if [ "$owner_type" = "Organization" ]; then
              owner_path="/orgs/${{ github.repository_owner }}"
            else
              owner_path="/users/${{ github.repository_owner }}"
            fi

            gh api -H "Accept: application/vnd.github+json" \
              "$owner_path/packages/nuget/${package_name}/versions?per_page=1" \
              --jq '.[0].name'
          }

          for project in $(find src/Packages -name "*.csproj"); do
            PACKAGE_NAME=$(basename "$project" .csproj)
            VERSION=$(grep -oP '(?<=<Version>).*?(?=</Version>)' "$project")

            echo "🔍 Check $PACKAGE_NAME version $VERSION..."

            LATEST_VERSION=$(get_latest_version "$PACKAGE_NAME")

            if [ "$VERSION" != "$LATEST_VERSION" ]; then
              echo "📦 Creating package $PACKAGE_NAME v$VERSION..."
              dotnet pack "$project" --configuration Release --output .
            else
              echo "✅ the package $PACKAGE_NAME is already in the latest version ($VERSION). Skipping publication."
            fi
          done

          # Publish only generated packages
          for package in *.nupkg; do
            echo "🚀 Publishing $package..."
            dotnet nuget push "$package" \
              --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
              --api-key "$NUGET_AUTH_TOKEN" \
              --skip-duplicate
          done
